[toolchain]
anchor_version = "0.31.1"
package_manager = "yarn"
solana_version = "2.1.20"

[features]
resolution = true
skip-lint = false

[programs.localnet]
example_iterative_resolution = "8mjNDtRMN7Sjq2ZVjCjKJUUaCfUdfZLoeYREmYs3yKSi"
executor_account_resolver_svm_program = "GeSLWQHGZRWhrdqo5Zvaa3JonhzQmfEmJSuHJwmRebPw"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
